name: Sed-replacer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "SnowGirl"
          replace: "Natsuki"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Welcome to TheNatsukiBot'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Sadew451
          commit_user_email: sadewofficial45@gmail.com
          commit_author: Sadew451 <sadewofficial45@gmail.com>
